# Generated by Django 4.0.3 on 2022-03-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyManage', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Especialidades',
            new_name='Especialidade',
        ),
    ]
