# Generated by Django 4.0.3 on 2022-03-26 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academyManage', '0002_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Scheduled consultation')),
                ('results', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academyManage.user')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('academyManage.user',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='client_since',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('PRO', 'Profissional'), ('CLIENTE', 'Cliente')], default='Cliente', max_length=20),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academyManage.user')),
                ('client_since', models.DateTimeField(verbose_name='Client Since')),
            ],
            bases=('academyManage.user',),
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('professional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academyManage.professional')),
                ('offered_schedules', models.DateTimeField(verbose_name='Class Schedule')),
            ],
            bases=('academyManage.professional',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('professional_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='academyManage.professional')),
                ('specialties', models.CharField(choices=[('SUPINO DE 20', 'Supino de 20'), ('CROSSFIT', 'Crossfit')], max_length=32)),
                ('offered_schedules', models.DateTimeField(verbose_name='Class Schedule')),
            ],
            bases=('academyManage.professional',),
        ),
        migrations.DeleteModel(
            name='Servico',
        ),
        migrations.AddField(
            model_name='consultation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyManage.user'),
        ),
    ]
