# Generated by Django 4.0.3 on 2022-03-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyManage', '0003_consultation_professional_remove_user_client_since_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
