# Generated by Django 4.0.3 on 2022-03-26 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyManage', '0004_remove_user_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='specialties',
        ),
    ]
