# Generated by Django 4.0.3 on 2022-05-02 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='payment_status',
            field=models.CharField(default='not_paid', max_length=50),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='client_desde',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Cliente desde'),
        ),
    ]
