# Generated by Django 4.0.3 on 2022-04-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='payment_status',
            field=models.CharField(default='not_paid', max_length=50),
        ),
    ]
