# Generated by Django 4.0.3 on 2022-03-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('especialidade', '0001_initial'),
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('cliente', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.medico')),
            ],
            options={
                'unique_together': {('medico', 'data_hora')},
            },
        ),
        migrations.CreateModel(
            name='Aula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('cliente', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuario.cliente')),
                ('especialidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidade.especialidade')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.professor')),
            ],
            options={
                'unique_together': {('professor', 'data_hora')},
            },
        ),
    ]
