# Generated by Django 4.0.3 on 2022-03-29 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('servico', '0002_alter_aula_cliente_alter_consulta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.medico'),
        ),
    ]
