# Generated by Django 4.0.3 on 2022-04-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('servico', '0004_alter_aula_cliente_alter_consulta_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aula',
            name='cliente',
        ),
        migrations.AddField(
            model_name='aula',
            name='alunos',
            field=models.ManyToManyField(to='usuario.cliente'),
        ),
        migrations.AddField(
            model_name='aula',
            name='max_alunos',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
