# Generated by Django 4.0.3 on 2022-04-27 05:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='cartao',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='data',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
